  fun take_error(simple': GSimpleAsyncResultI, error': NullablePointer[GErrorT]): None =>
    @g_simple_async_result_take_error(simple'.getptr(), error')
